### ISSUE TITLE
(SP: 2) [Sign up] Send e-mail when new client sign up

### ISSUE THREAD

**Issue by marianamartsy** [Space2Study-Project/Space2Study-BackEnd#48]
Description: e-mail error after client sign-up

Reproducible: always.

Preconditions:
The user is not logged in.

Steps to reproduce:

Click sign-up when client is registrating
Actual result:

![Image](https://github.com/Space2Study-Project/Space2Study-BackEnd/assets/123500008/5bc073df-3cd8-470c-bd97-0b43e5c9c13a)

Expected result:
e-mail sent

**Comment by vlad-khrychov** [comment]
Please make recording with setup of google cloud for mail sending.

**Comment by marianamartsy** [comment]
Video how it works:

https://www.loom.com/share/bde1844946c4432b8eb432042886adac
